package com.bkrn.user.entity;

public class BtUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_user.id
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_user.name
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_user.age
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bt_user.work
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    private String work;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_user.id
     *
     * @return the value of bt_user.id
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_user.id
     *
     * @param id the value for bt_user.id
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_user.name
     *
     * @return the value of bt_user.name
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_user.name
     *
     * @param name the value for bt_user.name
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_user.age
     *
     * @return the value of bt_user.age
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_user.age
     *
     * @param age the value for bt_user.age
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bt_user.work
     *
     * @return the value of bt_user.work
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bt_user.work
     *
     * @param work the value for bt_user.work
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }
}