package com.bkrn.user.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bkrn.user.entity.BtUser;
import com.bkrn.user.entity.BtUserExample;

public interface BtUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int countByExample(BtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int deleteByExample(BtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int insert(BtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int insertSelective(BtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    List<BtUser> selectByExample(BtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    BtUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") BtUser record, @Param("example") BtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int updateByExample(@Param("record") BtUser record, @Param("example") BtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int updateByPrimaryKeySelective(BtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bt_user
     *
     * @mbggenerated Wed Jan 24 11:58:16 CST 2018
     */
    int updateByPrimaryKey(BtUser record);
}